/**
 * Inventory IPC Handlers
 *
 * Thin wrapper around InventoryService for IPC communication.
 * Handles authentication checks and delegates to service layer.
 */

import { ipcMain } from "electron";
import {
  getInventoryService,
  inventoryLogger,
  getCategoryRepository,
  getProductSupplierRepository,
} from "@liratek/core";
import { requireRole } from "../session.js";
import { audit } from "./auditHelper.js";
import {
  ProductCreateSchema,
  ProductUpdateSchema,
  BatchUpdateSchema,
  StockAdjustSchema,
  validatePayload,
} from "../schemas/index.js";

// =============================================================================
// Types
// =============================================================================

interface ProductInput {
  id?: number;
  barcode: string;
  name: string;
  category: string;
  cost_price: number;
  retail_price: number;
  whish_price?: number;
  stock_quantity?: number;
  min_stock_level?: number;
  image_url?: string;
  supplier?: string | null;
}

// =============================================================================
// Handler Registration
// =============================================================================

export function registerInventoryHandlers(): void {
  const service = getInventoryService();

  // ---------------------------------------------------------------------------
  // Product Queries (No auth required for read operations)
  // ---------------------------------------------------------------------------

  // Get all products (optional filter by name/barcode)
  ipcMain.handle("inventory:get-products", (_event, search?: string) => {
    return service.getProducts(search);
  });

  // Get single product by ID
  ipcMain.handle("inventory:get-product", (_event, id: number) => {
    try {
      return service.getProductById(id);
    } catch (_error) {
      return null;
    }
  });

  // Get product by barcode
  ipcMain.handle(
    "inventory:get-product-by-barcode",
    (_event, barcode: string) => {
      return service.getProductByBarcode(barcode);
    },
  );

  // ---------------------------------------------------------------------------
  // Product CRUD (Admin only)
  // ---------------------------------------------------------------------------

  // Create product
  ipcMain.handle("inventory:create-product", (e, product: ProductInput) => {
    // Auth check
    try {
      const auth = requireRole(e.sender.id, ["admin", "staff"]);
      if (!auth.ok) return { success: false, error: auth.error };
    } catch {}

    // Validation — id must not be sent; it's auto-generated by the database
    const v = validatePayload(ProductCreateSchema, product);
    if (!v.ok) return { success: false, error: v.error };
    const validatedProduct = v.data;

    inventoryLogger.debug(
      { barcode: validatedProduct.barcode, name: validatedProduct.name },
      "Creating product",
    );
    // Auto-create category if needed and get its ID
    const categoryName = validatedProduct.category || "General";
    const categoryId = catRepo.getOrCreate(categoryName);

    // Auto-register product supplier if provided
    if (validatedProduct.supplier) {
      supplierRepo.getOrCreate(validatedProduct.supplier);
    }

    const result = service.createProduct({
      barcode: validatedProduct.barcode || null,
      name: validatedProduct.name,
      category: categoryName,
      category_id: categoryId,
      cost_price: validatedProduct.cost_price,
      retail_price: validatedProduct.retail_price,
      ...(validatedProduct.stock_quantity != null
        ? { stock_quantity: validatedProduct.stock_quantity }
        : {}),
      ...(validatedProduct.min_stock_level != null
        ? { min_stock_level: validatedProduct.min_stock_level }
        : {}),
      ...(validatedProduct.image_url != null
        ? { image_url: validatedProduct.image_url }
        : {}),
      supplier: validatedProduct.supplier ?? null,
    });
    audit(e.sender.id, {
      action: "create",
      entity_type: "product",
      entity_id: String((result as any)?.id ?? ""),
      summary: `Created product "${validatedProduct.name}" (${validatedProduct.barcode})`,
      new_values: {
        name: validatedProduct.name,
        barcode: validatedProduct.barcode,
        cost_price: validatedProduct.cost_price,
        retail_price: validatedProduct.retail_price,
      },
    });
    return result;
  });

  // Update product
  ipcMain.handle("inventory:update-product", (e, product: ProductInput) => {
    // Auth check
    try {
      const auth = requireRole(e.sender.id, ["admin", "staff"]);
      if (!auth.ok) return { success: false, error: auth.error };
    } catch {}

    // Validation — id is required by ProductUpdateSchema
    const v = validatePayload(ProductUpdateSchema, product);
    if (!v.ok) return { success: false, error: v.error };
    const validatedProduct = v.data;

    // Resolve category_id for the updated category
    const updCategoryName = validatedProduct.category || "General";
    const updCategoryId = catRepo.getOrCreate(updCategoryName);

    // Auto-register product supplier if provided
    if (validatedProduct.supplier) {
      supplierRepo.getOrCreate(validatedProduct.supplier);
    }

    const oldProduct = service.getProductById(validatedProduct.id);
    const result = service.updateProduct(validatedProduct.id, {
      barcode: validatedProduct.barcode,
      name: validatedProduct.name,
      category: updCategoryName,
      category_id: updCategoryId,
      cost_price: validatedProduct.cost_price,
      retail_price: validatedProduct.retail_price,
      min_stock_level: validatedProduct.min_stock_level ?? 5,
      ...(validatedProduct.image_url != null
        ? { image_url: validatedProduct.image_url }
        : {}),
      supplier: validatedProduct.supplier ?? null,
      stock_quantity: validatedProduct.stock_quantity,
    });
    audit(e.sender.id, {
      action: "update",
      entity_type: "product",
      entity_id: String(validatedProduct.id),
      summary: `Updated product "${validatedProduct.name}"`,
      old_values: oldProduct
        ? {
            name: oldProduct.name,
            cost_price: (oldProduct as any).cost_price,
            retail_price: (oldProduct as any).retail_price,
          }
        : undefined,
      new_values: {
        name: validatedProduct.name,
        cost_price: validatedProduct.cost_price,
        retail_price: validatedProduct.retail_price,
      },
    });
    return result;
  });

  // Soft delete product
  ipcMain.handle(
    "inventory:batch-update",
    async (
      _event,
      payload: {
        ids: number[];
        category?: string;
        min_stock_level?: number;
        supplier?: string | null;
      },
    ) => {
      // Validation
      const v = validatePayload(BatchUpdateSchema, payload);
      if (!v.ok) return { success: false, error: v.error };
      const validatedPayload = v.data;

      const result = service.batchUpdateProducts(validatedPayload.ids, {
        category: validatedPayload.category,
        min_stock_level: validatedPayload.min_stock_level,
        supplier: validatedPayload.supplier,
      });
      audit(_event.sender.id, {
        action: "update",
        entity_type: "product",
        summary: `Batch updated ${validatedPayload.ids.length} products`,
        metadata: { ids: validatedPayload.ids },
      });
      return result;
    },
  );

  ipcMain.handle("inventory:delete-product", (e, id: number) => {
    // Auth check
    try {
      const auth = requireRole(e.sender.id, ["admin", "staff"]);
      if (!auth.ok) return { success: false, error: auth.error };
    } catch {}

    const result = service.deleteProduct(id);
    audit(e.sender.id, {
      action: "delete",
      entity_type: "product",
      entity_id: String(id),
      summary: `Deleted product #${id}`,
    });
    return result;
  });

  ipcMain.handle("inventory:batch-delete", (e, ids: number[]) => {
    try {
      const auth = requireRole(e.sender.id, ["admin", "staff"]);
      if (!auth.ok) return { success: false, error: auth.error };
    } catch {}

    const result = service.batchDeleteProducts(ids);
    audit(e.sender.id, {
      action: "delete",
      entity_type: "product",
      summary: `Batch deleted ${ids.length} products`,
      metadata: { ids },
    });
    return result;
  });

  // ---------------------------------------------------------------------------
  // Stock Management (Admin only)
  // ---------------------------------------------------------------------------

  // Adjust stock — absolute set (newQuantity) or delta, always with a reason
  // (LIRA-077 audit trail). userId is injected from the authenticated
  // session, never trusted from the payload (rule 19c).
  ipcMain.handle(
    "inventory:adjust-stock",
    (
      e,
      payload: {
        id: number;
        newQuantity?: number;
        delta?: number;
        reason: string;
      },
    ) => {
      // Auth check
      let userId: number | null = null;
      try {
        const auth = requireRole(e.sender.id, ["admin", "staff"]);
        if (!auth.ok) return { success: false, error: auth.error };
        userId = auth.userId;
      } catch {}

      // Validation
      const v = validatePayload(StockAdjustSchema, payload);
      if (!v.ok) return { success: false, error: v.error };
      const { id, newQuantity, delta, reason } = v.data;

      const result =
        delta !== undefined
          ? service.adjustStockDelta(id, delta, reason, userId)
          : service.adjustStock(id, newQuantity as number, reason, userId);

      audit(e.sender.id, {
        action: "update",
        entity_type: "product",
        entity_id: String(id),
        summary:
          delta !== undefined
            ? `Adjusted stock for product #${id} by ${delta > 0 ? "+" : ""}${delta} (${reason})`
            : `Adjusted stock for product #${id} to ${newQuantity} (${reason})`,
        new_values: { newQuantity, delta, reason },
      });
      return result;
    },
  );

  // Stock adjustment audit history — one product, or the most recent across
  // all products when productId is omitted. Read-only: raw array, no
  // {success,data} envelope (mirrors getLowStockProducts/getNegativeStock).
  ipcMain.handle(
    "inventory:get-stock-adjustments",
    (_event, productId?: number) => {
      try {
        return service.getStockAdjustments(productId);
      } catch (error) {
        inventoryLogger.error({ error }, "Failed to get stock adjustments");
        return [];
      }
    },
  );

  // ---------------------------------------------------------------------------
  // Reporting (No auth required)
  // ---------------------------------------------------------------------------

  // Get Inventory Stock Stats (budget and count)
  ipcMain.handle("inventory:get-stock-stats", () => {
    try {
      return service.getStockStats();
    } catch (error) {
      inventoryLogger.error({ error }, "Failed to get stock stats");
      return { stock_budget_usd: 0, stock_count: 0 };
    }
  });

  // Get low stock products
  ipcMain.handle("inventory:get-low-stock-products", () => {
    try {
      return service.getLowStockProducts();
    } catch (error) {
      inventoryLogger.error({ error }, "Failed to get low stock products");
      return [];
    }
  });

  // Get products at negative stock (oversold before the stock guard — need
  // reconciliation; they can't be sold until the count is corrected)
  ipcMain.handle("inventory:get-negative-stock", () => {
    try {
      return service.getNegativeStockProducts();
    } catch (error) {
      inventoryLogger.error({ error }, "Failed to get negative-stock products");
      return [];
    }
  });

  // ---------------------------------------------------------------------------
  // Category Management
  // ---------------------------------------------------------------------------

  const catRepo = getCategoryRepository();
  const supplierRepo = getProductSupplierRepository();

  ipcMain.handle("inventory:get-categories", () => catRepo.getNames());
  ipcMain.handle("inventory:create-category", (_e, name: string) => {
    try {
      const result = catRepo.create(name);
      audit(_e.sender.id, {
        action: "create",
        entity_type: "category",
        entity_id: String(result.id),
        summary: `Created category "${name}"`,
      });
      return { success: true, ...result };
    } catch (e) {
      return { success: false, error: String(e) };
    }
  });
  ipcMain.handle(
    "inventory:update-category",
    (_e, id: number, name: string) => {
      try {
        const updated = catRepo.update(id, name);
        audit(_e.sender.id, {
          action: "update",
          entity_type: "category",
          entity_id: String(id),
          summary: `Updated category #${id} to "${name}"`,
        });
        return { success: true, updated };
      } catch (e) {
        return { success: false, error: String(e) };
      }
    },
  );
  ipcMain.handle("inventory:delete-category", (_e, id: number) => {
    try {
      const deleted = catRepo.delete(id);
      audit(_e.sender.id, {
        action: "delete",
        entity_type: "category",
        entity_id: String(id),
        summary: `Deleted category #${id}`,
      });
      return { success: true, deleted };
    } catch (e) {
      return { success: false, error: String(e) };
    }
  });
  ipcMain.handle("inventory:get-categories-full", () => catRepo.getAll());

  // ---------------------------------------------------------------------------
  // Product Supplier Management
  // ---------------------------------------------------------------------------

  ipcMain.handle("inventory:get-product-suppliers", () =>
    supplierRepo.getNames(),
  );
  ipcMain.handle("inventory:get-product-suppliers-full", () =>
    supplierRepo.getAllWithProductCount(),
  );
  ipcMain.handle("inventory:create-product-supplier", (_e, name: string) => {
    try {
      const result = supplierRepo.create(name);
      audit(_e.sender.id, {
        action: "create",
        entity_type: "product_supplier",
        entity_id: String(result.id),
        summary: `Created product supplier "${name}"`,
      });
      return { success: true, ...result };
    } catch (e) {
      return { success: false, error: String(e) };
    }
  });
  ipcMain.handle(
    "inventory:update-product-supplier",
    (_e, id: number, name: string) => {
      try {
        const updated = supplierRepo.update(id, name);
        audit(_e.sender.id, {
          action: "update",
          entity_type: "product_supplier",
          entity_id: String(id),
          summary: `Updated product supplier #${id} to "${name}"`,
        });
        return { success: true, updated };
      } catch (e) {
        return { success: false, error: String(e) };
      }
    },
  );
  ipcMain.handle("inventory:delete-product-supplier", (_e, id: number) => {
    try {
      const deleted = supplierRepo.delete(id);
      audit(_e.sender.id, {
        action: "delete",
        entity_type: "product_supplier",
        entity_id: String(id),
        summary: `Deleted product supplier #${id}`,
      });
      return { success: true, deleted };
    } catch (e) {
      return { success: false, error: String(e) };
    }
  });
}
